create table if not exists public.zenvoria_audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  actor_id text null,
  actor_email text null,
  actor_role text null,
  target_type text null,
  target_id text null,
  status text not null default 'success',
  ip text null,
  user_agent text null,
  metadata jsonb null,
  created_at timestamptz not null default now()
);

create index if not exists zenvoria_audit_logs_created_at_idx
  on public.zenvoria_audit_logs (created_at desc);

create index if not exists zenvoria_audit_logs_action_idx
  on public.zenvoria_audit_logs (action);

create index if not exists zenvoria_audit_logs_actor_email_idx
  on public.zenvoria_audit_logs (actor_email);
